### ISSUE TITLE
Update docker-compose for local builds/runs

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot-api#63]
The docker-compose should look like the below. However, the filer is reporting that the vlei-verifier is unhealthy but the healthcheck passes manually for me

- [ ] Determine what needs to be updated to have this docker compose pass all health checks so we can do debug and docker compose builds/run of the reg-pilot-api

```
services:
  reg-pilot-api:
    build:
      context: .
      dockerfile: ./images/reg-pilot-api.dockerfile
    image: gleif/reg-pilot-api:dev
    ports:
      - 8000:8000
    # command: python src/regps/app/fastapi_app.py
    volumes:
      - ./:/usr/src/app/regps
    environment:
      - VLEI_VERIFIER_URL=http://vlei-verifier:7676/
      - FILER_REPORTS=http://reg-pilot-filer:7878/reports/
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000/docs
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      - deps

  vlei-verifier:
    image: gleif/vlei-verifier:0.1.0
    container_name: vlei-verifier
    hostname: vlei-verifier
    environment:
      - VERIFIER_CONFIG_FILE=verifier-config-test.json
    ports:
      - 7676:7676
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7676/health
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      vlei-server:
        condition: service_healthy
      witness-demo:
        condition: service_healthy

  reg-pilot-filer:
    image: gleif/reg-pilot-filer:0.1.0
    container_name: reg-pilot-filer
    hostname: reg-pilot-filer
    ports:
      - 7878:7878
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7878/health
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    depends_on:
      vlei-verifier:
        condition: service_healthy

  vlei-server:
    image: gleif/vlei
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    command:
      - vLEI-server
      - -s
      - ./schema/acdc
      - -c
      - ./samples/acdc/
      - -o
      - ./samples/oobis/
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:7723/oobi/EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - 7723:7723

  witness-demo:
    image: weboftrust/keri-witness-demo:1.1.0
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5642/oobi"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    volumes:
      - ./config/witness-demo:/keripy/scripts/keri/cf/main
    ports:
      - 5642:5642
      - 5643:5643
      - 5644:5644

  deps:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      vlei-verifier:
        condition: service_healthy
      reg-pilot-filer:
        condition: service_healthy

  api:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      reg-pilot-api:
        condition: service_healthy

```
